sudo: required
language: java
jdk: oraclejdk8
addons:
 apt:
  packages:
  - libproj-dev
cache:
  directories:
  - geos-3.5.0
  - libspatialite-4.3.0a
before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - wget http://download.osgeo.org/geos/geos-3.5.0.tar.bz2
  - tar jxf geos-3.5.0.tar.bz2
  - cd geos-3.5.0 && ./configure && sudo make install
  - cd ..
  - wget http://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz
  - tar zxf libspatialite-4.3.0a.tar.gz
  - cd libspatialite-4.3.0a && ./configure --enable-freexl=no && sudo make install
  - cd ..
